# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.text_input_edit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.text_input_edit.setObjectName("text_input_edit")
        self.verticalLayout.addWidget(self.text_input_edit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.result_list = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.result_list.setObjectName("result_list")
        self.verticalLayout_2.addWidget(self.result_list)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rule_add_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rule_add_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rule_add_btn.setFont(font)
        self.rule_add_btn.setObjectName("rule_add_btn")
        self.horizontalLayout.addWidget(self.rule_add_btn)
        self.rule_remove_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rule_remove_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rule_remove_btn.setFont(font)
        self.rule_remove_btn.setObjectName("rule_remove_btn")
        self.horizontalLayout.addWidget(self.rule_remove_btn)
        self.rule_up_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rule_up_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rule_up_btn.setFont(font)
        self.rule_up_btn.setObjectName("rule_up_btn")
        self.horizontalLayout.addWidget(self.rule_up_btn)
        self.rule_down_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rule_down_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rule_down_btn.setObjectName("rule_down_btn")
        self.horizontalLayout.addWidget(self.rule_down_btn)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.rule_apply_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rule_apply_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rule_apply_btn.setFont(font)
        self.rule_apply_btn.setObjectName("rule_apply_btn")
        self.horizontalLayout.addWidget(self.rule_apply_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.rule_list = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.rule_list.setDragEnabled(False)
        self.rule_list.setObjectName("rule_list")
        self.verticalLayout_3.addWidget(self.rule_list)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.rule_template_edit = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.rule_template_edit.setObjectName("rule_template_edit")
        self.verticalLayout_4.addWidget(self.rule_template_edit)
        self.gridLayout.addWidget(self.splitter_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 23))
        self.menubar.setObjectName("menubar")
        self.menuAfqk = QtWidgets.QMenu(self.menubar)
        self.menuAfqk.setObjectName("menuAfqk")
        MainWindow.setMenuBar(self.menubar)
        self.action_load_rule = QtWidgets.QAction(MainWindow)
        self.action_load_rule.setObjectName("action_load_rule")
        self.action_save_rule = QtWidgets.QAction(MainWindow)
        self.action_save_rule.setObjectName("action_save_rule")
        self.action_load_text = QtWidgets.QAction(MainWindow)
        self.action_load_text.setObjectName("action_load_text")
        self.action_save_text = QtWidgets.QAction(MainWindow)
        self.action_save_text.setObjectName("action_save_text")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_save_as_rule = QtWidgets.QAction(MainWindow)
        self.action_save_as_rule.setObjectName("action_save_as_rule")
        self.action_save_as_text = QtWidgets.QAction(MainWindow)
        self.action_save_as_text.setObjectName("action_save_as_text")
        self.menuAfqk.addAction(self.action_load_rule)
        self.menuAfqk.addAction(self.action_save_rule)
        self.menuAfqk.addAction(self.action_save_as_rule)
        self.menuAfqk.addSeparator()
        self.menuAfqk.addAction(self.action_load_text)
        self.menuAfqk.addAction(self.action_save_text)
        self.menuAfqk.addAction(self.action_save_as_text)
        self.menuAfqk.addSeparator()
        self.menuAfqk.addAction(self.action_exit)
        self.menubar.addAction(self.menuAfqk.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Пунктуатор"))
        self.label.setText(_translate("MainWindow", "Текст"))
        self.label_2.setText(_translate("MainWindow", "Результат"))
        self.label_3.setText(_translate("MainWindow", "Правила"))
        self.rule_add_btn.setText(_translate("MainWindow", "+"))
        self.rule_remove_btn.setText(_translate("MainWindow", "-"))
        self.rule_up_btn.setText(_translate("MainWindow", "▲"))
        self.rule_up_btn.setShortcut(_translate("MainWindow", "Ctrl+Up"))
        self.rule_down_btn.setText(_translate("MainWindow", "▼"))
        self.rule_down_btn.setShortcut(_translate("MainWindow", "Ctrl+Down"))
        self.rule_apply_btn.setText(_translate("MainWindow", "↻"))
        self.label_4.setText(_translate("MainWindow", "Шаблоны"))
        self.menuAfqk.setTitle(_translate("MainWindow", "Файл"))
        self.action_load_rule.setText(_translate("MainWindow", "Загрузить правила"))
        self.action_save_rule.setText(_translate("MainWindow", "Сохранить правила"))
        self.action_load_text.setText(_translate("MainWindow", "Загрузить текст"))
        self.action_save_text.setText(_translate("MainWindow", "Сохранить текст"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
        self.action_save_as_rule.setText(_translate("MainWindow", "Сохранить правила как..."))
        self.action_save_as_text.setText(_translate("MainWindow", "Сохранить текст как..."))

