# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_4.addWidget(self.line_5)
        self.btn_text_load = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_text_load.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_text_load.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_text_load.setIcon(icon)
        self.btn_text_load.setIconSize(QtCore.QSize(24, 18))
        self.btn_text_load.setObjectName("btn_text_load")
        self.horizontalLayout_4.addWidget(self.btn_text_load)
        self.btn_text_save = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_text_save.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_text_save.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/file-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_text_save.setIcon(icon1)
        self.btn_text_save.setIconSize(QtCore.QSize(24, 18))
        self.btn_text_save.setObjectName("btn_text_save")
        self.horizontalLayout_4.addWidget(self.btn_text_save)
        self.btn_text_save_as = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_text_save_as.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_text_save_as.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/file-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_text_save_as.setIcon(icon2)
        self.btn_text_save_as.setIconSize(QtCore.QSize(24, 18))
        self.btn_text_save_as.setObjectName("btn_text_save_as")
        self.horizontalLayout_4.addWidget(self.btn_text_save_as)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.table_data = QtWidgets.QTableView(self.verticalLayoutWidget_2)
        self.table_data.setObjectName("table_data")
        self.verticalLayout_2.addWidget(self.table_data)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.btn_rule_apply = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rule_apply.setEnabled(True)
        self.btn_rule_apply.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_rule_apply.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/check-alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rule_apply.setIcon(icon3)
        self.btn_rule_apply.setIconSize(QtCore.QSize(24, 18))
        self.btn_rule_apply.setObjectName("btn_rule_apply")
        self.horizontalLayout.addWidget(self.btn_rule_apply)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.btn_rule_add = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rule_add.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_rule_add.setFont(font)
        self.btn_rule_add.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rule_add.setIcon(icon4)
        self.btn_rule_add.setIconSize(QtCore.QSize(24, 18))
        self.btn_rule_add.setObjectName("btn_rule_add")
        self.horizontalLayout.addWidget(self.btn_rule_add)
        self.btn_rule_remove = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rule_remove.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_rule_remove.setFont(font)
        self.btn_rule_remove.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rule_remove.setIcon(icon5)
        self.btn_rule_remove.setIconSize(QtCore.QSize(24, 18))
        self.btn_rule_remove.setObjectName("btn_rule_remove")
        self.horizontalLayout.addWidget(self.btn_rule_remove)
        self.btn_rule_up = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rule_up.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_rule_up.setFont(font)
        self.btn_rule_up.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/arrow-1-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rule_up.setIcon(icon6)
        self.btn_rule_up.setIconSize(QtCore.QSize(24, 18))
        self.btn_rule_up.setObjectName("btn_rule_up")
        self.horizontalLayout.addWidget(self.btn_rule_up)
        self.btn_rule_down = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rule_down.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_rule_down.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/arrow-1-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rule_down.setIcon(icon7)
        self.btn_rule_down.setIconSize(QtCore.QSize(24, 18))
        self.btn_rule_down.setObjectName("btn_rule_down")
        self.horizontalLayout.addWidget(self.btn_rule_down)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.btn_rule_load = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rule_load.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_rule_load.setText("")
        self.btn_rule_load.setIcon(icon)
        self.btn_rule_load.setIconSize(QtCore.QSize(24, 18))
        self.btn_rule_load.setObjectName("btn_rule_load")
        self.horizontalLayout.addWidget(self.btn_rule_load)
        self.btn_rule_save = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rule_save.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_rule_save.setText("")
        self.btn_rule_save.setIcon(icon1)
        self.btn_rule_save.setIconSize(QtCore.QSize(24, 19))
        self.btn_rule_save.setObjectName("btn_rule_save")
        self.horizontalLayout.addWidget(self.btn_rule_save)
        self.btn_rule_save_as = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_rule_save_as.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_rule_save_as.setText("")
        self.btn_rule_save_as.setIcon(icon2)
        self.btn_rule_save_as.setIconSize(QtCore.QSize(24, 19))
        self.btn_rule_save_as.setObjectName("btn_rule_save_as")
        self.horizontalLayout.addWidget(self.btn_rule_save_as)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.rule_list = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.rule_list.setDragEnabled(False)
        self.rule_list.setObjectName("rule_list")
        self.verticalLayout_3.addWidget(self.rule_list)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.btn_rule_check = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_rule_check.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/3D-Z-Axis-Rotation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rule_check.setIcon(icon8)
        self.btn_rule_check.setIconSize(QtCore.QSize(24, 18))
        self.btn_rule_check.setObjectName("btn_rule_check")
        self.horizontalLayout_3.addWidget(self.btn_rule_check)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.rule_template_edit = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.rule_template_edit.setObjectName("rule_template_edit")
        self.verticalLayout_4.addWidget(self.rule_template_edit)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 25))
        self.menubar.setObjectName("menubar")
        self.menuAfqk = QtWidgets.QMenu(self.menubar)
        self.menuAfqk.setObjectName("menuAfqk")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action_rule_load = QtWidgets.QAction(MainWindow)
        self.action_rule_load.setIcon(icon)
        self.action_rule_load.setIconVisibleInMenu(True)
        self.action_rule_load.setObjectName("action_rule_load")
        self.action_rule_save = QtWidgets.QAction(MainWindow)
        self.action_rule_save.setIcon(icon1)
        self.action_rule_save.setIconVisibleInMenu(True)
        self.action_rule_save.setObjectName("action_rule_save")
        self.action_text_load = QtWidgets.QAction(MainWindow)
        self.action_text_load.setIcon(icon)
        self.action_text_load.setIconVisibleInMenu(True)
        self.action_text_load.setObjectName("action_text_load")
        self.action_text_save = QtWidgets.QAction(MainWindow)
        self.action_text_save.setIcon(icon1)
        self.action_text_save.setIconVisibleInMenu(True)
        self.action_text_save.setObjectName("action_text_save")
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon9)
        self.action_exit.setIconVisibleInMenu(True)
        self.action_exit.setObjectName("action_exit")
        self.action_rule_save_as = QtWidgets.QAction(MainWindow)
        self.action_rule_save_as.setIcon(icon2)
        self.action_rule_save_as.setIconVisibleInMenu(True)
        self.action_rule_save_as.setObjectName("action_rule_save_as")
        self.action_text_save_as = QtWidgets.QAction(MainWindow)
        self.action_text_save_as.setIcon(icon2)
        self.action_text_save_as.setIconVisibleInMenu(True)
        self.action_text_save_as.setObjectName("action_text_save_as")
        self.action_rule_add = QtWidgets.QAction(MainWindow)
        self.action_rule_add.setIcon(icon4)
        self.action_rule_add.setIconVisibleInMenu(True)
        self.action_rule_add.setObjectName("action_rule_add")
        self.action_rule_remove = QtWidgets.QAction(MainWindow)
        self.action_rule_remove.setIcon(icon5)
        self.action_rule_remove.setIconVisibleInMenu(True)
        self.action_rule_remove.setObjectName("action_rule_remove")
        self.action_rule_up = QtWidgets.QAction(MainWindow)
        self.action_rule_up.setIcon(icon6)
        self.action_rule_up.setIconVisibleInMenu(True)
        self.action_rule_up.setObjectName("action_rule_up")
        self.action_rule_down = QtWidgets.QAction(MainWindow)
        self.action_rule_down.setIcon(icon7)
        self.action_rule_down.setIconVisibleInMenu(True)
        self.action_rule_down.setObjectName("action_rule_down")
        self.action_rule_apply = QtWidgets.QAction(MainWindow)
        self.action_rule_apply.setIcon(icon3)
        self.action_rule_apply.setIconVisibleInMenu(True)
        self.action_rule_apply.setObjectName("action_rule_apply")
        self.action_rule_check = QtWidgets.QAction(MainWindow)
        self.action_rule_check.setIcon(icon8)
        self.action_rule_check.setIconVisibleInMenu(True)
        self.action_rule_check.setObjectName("action_rule_check")
        self.action_settings_font = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_settings_font.setIcon(icon10)
        self.action_settings_font.setIconVisibleInMenu(True)
        self.action_settings_font.setObjectName("action_settings_font")
        self.action_settings_hotkey = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_settings_hotkey.setIcon(icon11)
        self.action_settings_hotkey.setIconVisibleInMenu(True)
        self.action_settings_hotkey.setObjectName("action_settings_hotkey")
        self.menuAfqk.addAction(self.action_rule_load)
        self.menuAfqk.addAction(self.action_rule_save)
        self.menuAfqk.addAction(self.action_rule_save_as)
        self.menuAfqk.addSeparator()
        self.menuAfqk.addAction(self.action_text_load)
        self.menuAfqk.addAction(self.action_text_save)
        self.menuAfqk.addAction(self.action_text_save_as)
        self.menuAfqk.addSeparator()
        self.menuAfqk.addAction(self.action_exit)
        self.menu.addAction(self.action_rule_add)
        self.menu.addAction(self.action_rule_remove)
        self.menu.addAction(self.action_rule_up)
        self.menu.addAction(self.action_rule_down)
        self.menu.addSeparator()
        self.menu.addAction(self.action_rule_apply)
        self.menu.addAction(self.action_rule_check)
        self.menubar.addAction(self.menuAfqk.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Пунктуатор"))
        self.label_2.setText(_translate("MainWindow", "Данные"))
        self.btn_text_load.setToolTip(_translate("MainWindow", "Загрузить текст"))
        self.btn_text_save.setToolTip(_translate("MainWindow", "Сохранить текст"))
        self.btn_text_save_as.setToolTip(_translate("MainWindow", "Сохранить текст как..."))
        self.label_3.setText(_translate("MainWindow", "Правила"))
        self.btn_rule_apply.setToolTip(_translate("MainWindow", "Применить правила"))
        self.btn_rule_apply.setText(_translate("MainWindow", "Применить"))
        self.btn_rule_add.setToolTip(_translate("MainWindow", "Добавить правило"))
        self.btn_rule_remove.setToolTip(_translate("MainWindow", "Удалить правило"))
        self.btn_rule_up.setToolTip(_translate("MainWindow", "Повысить приоритет правила"))
        self.btn_rule_down.setToolTip(_translate("MainWindow", "Понизить приоритет правила"))
        self.btn_rule_load.setToolTip(_translate("MainWindow", "Загрузить правила"))
        self.btn_rule_save.setToolTip(_translate("MainWindow", "Сохранить правила"))
        self.btn_rule_save_as.setToolTip(_translate("MainWindow", "Сохранить правила как..."))
        self.label.setText(_translate("MainWindow", "Шаблоны"))
        self.btn_rule_check.setToolTip(_translate("MainWindow", "Проверить шаблоны"))
        self.btn_rule_check.setText(_translate("MainWindow", "Проверить"))
        self.menuAfqk.setTitle(_translate("MainWindow", "Файл"))
        self.menu.setTitle(_translate("MainWindow", "Правило"))
        self.action_rule_load.setText(_translate("MainWindow", "Загрузить правила"))
        self.action_rule_save.setText(_translate("MainWindow", "Сохранить правила"))
        self.action_text_load.setText(_translate("MainWindow", "Загрузить текст"))
        self.action_text_save.setText(_translate("MainWindow", "Сохранить текст"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
        self.action_rule_save_as.setText(_translate("MainWindow", "Сохранить правила как..."))
        self.action_rule_save_as.setToolTip(_translate("MainWindow", "Сохранить правила как..."))
        self.action_text_save_as.setText(_translate("MainWindow", "Сохранить текст как..."))
        self.action_rule_add.setText(_translate("MainWindow", "Добавить"))
        self.action_rule_remove.setText(_translate("MainWindow", "Удалить"))
        self.action_rule_up.setText(_translate("MainWindow", "Вверх"))
        self.action_rule_down.setText(_translate("MainWindow", "Вниз"))
        self.action_rule_apply.setText(_translate("MainWindow", "Применить правила"))
        self.action_rule_check.setText(_translate("MainWindow", "Проверить шаблоны"))
        self.action_settings_font.setText(_translate("MainWindow", "Горячие клавиши"))
        self.action_settings_hotkey.setText(_translate("MainWindow", "Шрифт"))

